user input for PRIME_LIMIT server.py
AbhinavRobinson/RSA-over-SHA pull request #2
Opened 2020-10-03 10:53 UTC by REGATTE

2020-10-03 10:59 UTC, AbhinavRobinson commented on server.py
> +print("initialising model")
remove this

2020-10-03 11:00 UTC, AbhinavRobinson requested changes

2020-10-03 11:00 UTC, AbhinavRobinson commented on server.py
> +print("initialising model")
remove this

2020-10-03 11:00 UTC, AbhinavRobinson commented on server.py
> +    PRIME_LIMIT = int(input("enter a int value to mark the upper bound"))
okay

2020-10-03 11:00 UTC, AbhinavRobinson commented on server.py
> +    print("socket is initialising")
okay

2020-10-03 11:04 UTC, merged

2020-10-04 16:36 UTC, aniketbiprojit reviewed
Cheeku ki Chuchi wOrKs.

2020-10-11 16:21 UTC, AbhinavRobinson commented
Done.

2020-10-19 03:33 UTC, AbhinavRobinson reviewed
Retrospect

2020-10-19 03:33 UTC, AbhinavRobinson commented on server.py
> +    PRIME_LIMIT = int(input("Enter PRIME the upper bound (1000,1000000000): "))
Should be removed later, not necessary.